// That the preview and the writer produce the same bytes.
//
// The page now shows an administrator the inline policy their choices will become. That is only
// worth having if it is the policy that actually gets written - a preview that differs from the
// deployed document is a wrong answer with a screenshot, and worse than no preview at all, because
// somebody approves against it.
//
// The authority is event_pipeline/code/generator/restriction.py. It is Python and this is Node, so
// they cannot share the code; what they share instead is fixtures. server/fixtures/inline-preview.json
// is generated BY the Python from a set of decisions, carrying the exact bytes it composed, and
// every case here re-composes the same decisions in JavaScript and demands the same string.
//
// Regenerate after changing restriction.py:
//
//     cd event_pipeline && python3 scripts/gen_inline_preview_fixture.py
//     npm run check
//
// Existing cases are rebuilt from the decisions already in the file, so only the bytes move.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import {
  INLINE_LIMIT, composeInline, creationExemption, denySidBase, fenceSid, inlineBytes,
  policyContribution, readable, readableStatements,
  serialise, subResource,
} from './inlinePreview.js';

const FIXTURES = JSON.parse(
  readFileSync(new URL('./fixtures/inline-preview.json', import.meta.url), 'utf8'),
);

/**
 * The shape a fence is composed from: the attachment that opened the hole, in the assessment's
 * passrole_grants form. `identifier` and `source` are what the Sid is made of, `services` is what
 * the statements are made of - one per service, because NotResource is per service.
 */
const LAMBDA_GRANT = {
  identifier: 'arn:aws:iam::aws:policy/AWSLambda_FullAccess',
  source: 'aws_managed',
  services: ['lambda.amazonaws.com'],
};

/**
 * The one thing the JavaScript cannot work out for itself: whether an action operates BELOW the
 * resource an index can hold. The Python knows from the action table; the fixture carries its
 * answer; the page gets the same answer from action_reference.nested_types.
 */
const nestedOf = (c) => {
  const set = new Set(c.nested_actions ?? []);
  return (action) => set.has(action);
};

/**
 * Same arrangement for the creation-exemption patterns: the Python knows them from the table, the
 * fixture carries them, and the page gets the same answer from action_reference.created_formats.
 */
const createdOf = (c) => {
  const map = c.created_formats ?? {};
  return (action) => map[action] ?? [];
};

test('the fence Sid is the name the Python derived, edges included', () => {
  // The Sid is the one part of the fence a composed case cannot pin on its own: a case exercises
  // the two or three policy names it happens to carry, and the rule has edges no realistic case
  // reaches - the absorbed AWS/cmp prefix, the separators IAM refuses, an identifier that survives
  // stripping as nothing, a grant with no `source` where the ARN has to answer. So the fixture
  // carries the Python's fence_sid() over a table of those, and this demands the same string. A
  // preview naming a statement differently from the writer is the screenshot somebody approves.
  const table = FIXTURES.fence_sids ?? [];
  assert.ok(table.length > 0, 'the fixture carries no fence names - regenerate it');
  for (const row of table) {
    assert.equal(fenceSid(row.identifier, row.source), row.sid,
                 `${JSON.stringify(row.identifier)} (${row.source}): the preview and `
                 + 'generator/restriction.py name the fence differently');
  }
  // And every one of them is a Sid IAM will take.
  for (const row of table) assert.match(row.sid, /^[0-9A-Za-z]+$/, row.sid);
});

test('the restriction Sid base is the name the Python derived, cut at the same character', () => {
  // Same argument as the fence above, plus one this family has and the fence does not: the base is
  // CUT to config.sid_policy_name_limit, and a preview cutting at a different character names a
  // statement the writer will not write. The table also carries the pair that collides after the
  // cut - the container refuses those, and the preview has to reach the same two names for the
  // refusal to be about anything at all.
  const table = FIXTURES.deny_sid_bases ?? [];
  assert.ok(table.length > 0, 'the fixture carries no restriction Sid bases - regenerate it');
  for (const row of table) {
    assert.equal(denySidBase(row.identifier), row.base,
                 `${JSON.stringify(row.identifier)}: the preview and generator/restriction.py `
                 + 'name the restriction differently');
  }
  for (const row of table) assert.match(row.base, /^[0-9A-Za-z]+$/, row.base);
});

test('every fixture composes to the bytes the container composed', () => {
  for (const c of FIXTURES.cases) {
    const document = composeInline(c.restrictions, {
      accountId: c.account_id ?? FIXTURES.account_id,
      fenceGrants: c.fence_grants ?? [],
      nested: nestedOf(c),
      createdFormats: createdOf(c),
    });
    assert.equal(serialise(document), c.serialised,
                 `${c.label}: the preview and generator/restriction.py disagree`);
    assert.equal(inlineBytes(document), c.bytes, `${c.label}: byte count`);
  }
});

test('a container ARN brings what is inside it, and only where it should', () => {
  // The bug in one line: arn:aws:s3:::b does not match arn:aws:s3:::b/key, so a NotResource list of
  // bucket ARNs denied every object operation INSIDE the buckets it was there to keep.
  const bucket = 'arn:aws:s3:::opt-solution-markers';
  const one = (action, nested) => composeInline(
    [{ policy: 'p', intent: 'allow_only', actions: [action], resources: [bucket] }],
    { accountId: FIXTURES.account_id, nested: () => nested },
  ).Statement[0];
  assert.deepEqual(one('s3:GetObject', true).NotResource, [bucket, `${bucket}/*`]);
  // And not where the resource has nothing under it. ssm has no child type, and /* on a parameter
  // ARN would put every parameter below it in the same list.
  assert.deepEqual(one('s3:GetBucketPolicy', false).NotResource, [bucket]);
});

test('the separator is read off the ARN, not assumed', () => {
  // Taking the LAST separator is the version that looks right and gets log groups wrong: the '/' in
  // the group name comes after the ':' that follows the type.
  assert.equal(subResource('arn:aws:s3:::b'), 'arn:aws:s3:::b/*');
  assert.equal(subResource('arn:aws:dynamodb:us-east-1:1:table/t'),
               'arn:aws:dynamodb:us-east-1:1:table/t/*');
  assert.equal(subResource('arn:aws:lambda:us-east-1:1:function:fn'),
               'arn:aws:lambda:us-east-1:1:function:fn:*');
  assert.equal(subResource('arn:aws:logs:us-east-1:1:log-group:/aws/lambda/x'),
               'arn:aws:logs:us-east-1:1:log-group:/aws/lambda/x:*');
});

test('the fixtures actually exercise both answers', () => {
  // A fixture set where nothing was nested would pass while the JavaScript never expanded anything.
  assert.ok(FIXTURES.cases.some((c) => (c.nested_actions ?? []).length > 0),
            'no fixture covers an action that acts below the picked resource');
  assert.ok(FIXTURES.cases.some((c) => (c.nested_actions ?? []).length === 0
                                       && (c.restrictions ?? []).length > 0),
            'no fixture covers an action that acts on the picked resource itself');
});

test('the fixtures actually cover the fold, in both directions', () => {
  // A fixture set that only had foldable cases would pass while the JS folded everything.
  const folded = FIXTURES.cases.find((c) => c.label.includes('접힌다'));
  const kept = FIXTURES.cases.find((c) => c.label.includes('접히지 않는다'));
  assert.ok(folded && kept, 'the fixtures no longer pin both sides of the fold');
  assert.equal(composeInline(folded.restrictions, { accountId: FIXTURES.account_id })
    .Statement.length, 1);
  assert.equal(composeInline(kept.restrictions, { accountId: FIXTURES.account_id })
    .Statement.length, 2, 'two different resource lists were folded into one');
});

test('the serialiser sorts keys and emits no whitespace', () => {
  // Both halves are load-bearing. No whitespace is why the byte count can be compared to a
  // NON-whitespace quota without stripping anything; sorted keys are why two processes composing
  // the same decisions get the same digest.
  assert.equal(serialise({ b: 1, a: [3, 2] }), '{"a":[3,2],"b":1}');
  assert.ok(!/\s/.test(serialise({ Statement: [{ Sid: 'x', Effect: 'Deny' }] })));
});

test('one action stays a string and two become a sorted array', () => {
  const one = composeInline([{ intent: 'allow_only', actions: ['s3:PutObject'],
                              resources: ['arn:aws:s3:::b'] }], { accountId: '1' });
  assert.equal(one.Statement[0].Action, 's3:PutObject');
  const two = composeInline([{ intent: 'allow_only', actions: ['s3:PutObject', 's3:DeleteObject'],
                              resources: ['arn:aws:s3:::b'] }], { accountId: '1' });
  assert.deepEqual(two.Statement[0].Action, ['s3:DeleteObject', 's3:PutObject']);
});

test('the order the administrator ticked things in does not change the document', () => {
  // Otherwise the same restriction reads as a change every time it is re-opened, and a terraform
  // plan over an unchanged one has a diff in it.
  const a = [{ intent: 'allow_only', actions: ['s3:PutObject'], resources: ['arn:aws:s3:::z', 'arn:aws:s3:::a'] },
             { intent: 'allow_only', actions: ['s3:GetObject'], resources: ['arn:aws:s3:::a'] }];
  assert.equal(serialise(composeInline(a, { accountId: '1' })),
               serialise(composeInline([...a].reverse(), { accountId: '1' })));
});

test('the fence is in the document, because it spends the same quota', () => {
  // An approver who reads the preview must not find a statement in the deployed version that the
  // preview did not have - and the fence is the one the pipeline adds on its own.
  const withFence = composeInline([], { accountId: '718100330247', fenceGrants: [LAMBDA_GRANT] });
  assert.equal(withFence.Statement.length, 1);
  // And the Sid says which attachment opened the hole, not just that a fence is there.
  assert.equal(withFence.Statement[0].Sid, 'ampLambdaFullAccessFence');
  assert.equal(composeInline([], { accountId: '1' }).Statement.length, 0);
});

test('the fold is what keeps a wide restriction under the quota', () => {
  // The reason it exists. Twenty actions over forty kept ARNs wrote those ARNs twenty times.
  const resources = Array.from({ length: 40 }, (_, i) => `arn:aws:s3:::bucket-${String(i).padStart(3, '0')}`);
  const restrictions = Array.from({ length: 20 }, (_, i) => ({
    intent: 'allow_only', actions: [`s3:Action${String(i).padStart(2, '0')}`], resources,
  }));
  const document = composeInline(restrictions, { accountId: '1' });
  assert.equal(document.Statement.length, 1);
  assert.ok(inlineBytes(document) < INLINE_LIMIT, `${inlineBytes(document)} bytes`);
});

test('what a person reads is indented and in the order a policy is written', () => {
  // The bytes above are for the quota and the digest. This is the one an approver looks at, and
  // Sid-Effect-Action-Resource is the order every IAM document in the world is written in.
  const text = readable(composeInline(
    [{ intent: 'allow_only', actions: ['s3:PutObject'], resources: ['arn:aws:s3:::b'] }],
    { accountId: '1' },
  ));
  assert.ok(text.includes('\n  '), 'the readable form is not indented');
  const first = text.indexOf('"Sid"');
  assert.ok(first < text.indexOf('"Effect"'));
  assert.ok(text.indexOf('"Effect"') < text.indexOf('"Action"'));
  assert.ok(text.indexOf('"Action"') < text.indexOf('"NotResource"'));
});

// ---- one policy's part of the shared document ---------------------------------------------------

const BUCKET = 'arn:aws:s3:::opt-solution-markers';
const OTHER = 'arn:aws:s3:::opt-solution-plans';

test("a policy's excerpt carries the Sids the document will be WRITTEN under", () => {
  // The whole reason this reads a composed document rather than composing one of its own. Two
  // policies, four statements; the second policy's are AdminDeny2 and AdminDeny4, and renumbering
  // them to 1 and 2 would produce a document nobody will write - which an approver would then
  // screenshot and match against a deployed policy that says something else.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'B', intent: 'deny_only', actions: ['s3:PutObject'], resources: [OTHER] },
    { policy: 'A', intent: 'deny_action', actions: ['s3:CreateBucket'] },
    { policy: 'B', intent: 'allow_only', actions: ['s3:DeleteObject'], resources: [OTHER] },
  ];
  const whole = composeInline(restrictions, { accountId: '1' });
  const b = policyContribution(restrictions, 'B', { accountId: '1' });

  const sids = b.statements.map((s) => s.statement.Sid);
  assert.equal(sids.length, 2);
  for (const sid of sids) {
    assert.ok(whole.Statement.some((one) => one.Sid === sid),
              `${sid} is not a Sid of the document that gets written`);
  }
  // Every statement it names is the one from the whole document, not a rebuilt copy.
  for (const { statement } of b.statements) {
    assert.equal(serialise(statement),
                 serialise(whole.Statement.find((one) => one.Sid === statement.Sid)));
  }
  // And nothing of A's is in it.
  assert.ok(!b.statements.some((s) => s.ours.includes('s3:GetObject')));
});

test('the same action on different resources does not put one policy in the other', () => {
  // The failure this closed: matching on the ACTION NAME put both statements in both excerpts, so
  // each policy's view showed a Deny on a bucket it had nothing to do with. Attribution moved to
  // the clause and then to the Sid family, and the property has to survive both moves.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'B', intent: 'deny_only', actions: ['s3:GetObject'], resources: [OTHER] },
  ];
  const whole = composeInline(restrictions, { accountId: '1' });
  assert.equal(whole.Statement.length, 2, 'they folded, so this tests nothing');

  for (const [policy, bucket] of [['A', BUCKET], ['B', OTHER]]) {
    const view = policyContribution(restrictions, policy, { accountId: '1' });
    assert.equal(view.statements.length, 1, `${policy} was given the other policy's statement`);
    assert.deepEqual(view.statements[0].statement.Resource, [bucket], policy);
  }
});

test('the clause used for attribution is the one the writer folds on', () => {
  // Not a re-derivation. The excerpt calls the same statement() and clause() the fold calls, so a
  // change to how a resource clause is composed cannot move the fold and leave attribution behind -
  // an allow_only whose bucket brings its objects in is one clause, and the excerpt has to key on
  // the expanded one, not the picked one.
  const nested = (action) => action === 's3:GetObject';
  const restrictions = [
    { policy: 'A', intent: 'allow_only', actions: ['s3:GetObject'], resources: [BUCKET] },
  ];
  const view = policyContribution(restrictions, 'A', { accountId: '1', nested });
  assert.equal(view.statements.length, 1, 'sub-resource expansion broke the attribution');
  assert.deepEqual(view.statements[0].statement.NotResource, [BUCKET, `${BUCKET}/*`]);
});

test('a statement has one owner, and its Sid says which', () => {
  // What replaced co-ownership. The fold runs inside one attached policy's group, so two policies
  // denying different actions on the same bucket produce TWO statements rather than one carrying
  // both - and each excerpt is exactly its own policy's, with nothing to disclaim.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'B', intent: 'deny_only', actions: ['s3:PutObject'], resources: [BUCKET] },
  ];
  const whole = composeInline(restrictions, { accountId: '1' });
  assert.equal(whole.Statement.length, 2, 'the two folded together, which no Sid could name');
  assert.deepEqual(whole.Statement.map((s) => s.Sid),
                   [`${denySidBase('A')}1`, `${denySidBase('B')}1`]);

  for (const [policy, ours] of [['A', 's3:GetObject'], ['B', 's3:PutObject']]) {
    const view = policyContribution(restrictions, policy, { accountId: '1' });
    assert.equal(view.statements.length, 1, policy);
    assert.deepEqual(view.statements[0].ours, [ours], policy);
    assert.equal(view.statements[0].statement.Action, ours, policy);
    assert.equal(view.statements[0].statement.Sid, `${denySidBase(policy)}1`, policy);
  }
});

test('a base that begins another base does not claim its statements', () => {
  // Bases are alphanumeric, so one can be a prefix of another and a startsWith test would hand
  // AdminDenyCmpWebHosting1 to the policy called Web. The anchored digits are what stop it.
  const restrictions = [
    { policy: 'cmp-Web', intent: 'deny_action', actions: ['s3:GetObject'] },
    { policy: 'cmp-WebHosting', intent: 'deny_action', actions: ['s3:PutObject'] },
  ];
  assert.ok(denySidBase('cmp-WebHosting').startsWith(denySidBase('cmp-Web')),
            'the two bases no longer overlap, so this tests nothing');
  const view = policyContribution(restrictions, 'cmp-Web', { accountId: '1' });
  assert.equal(view.statements.length, 1);
  assert.deepEqual(view.statements[0].ours, ['s3:GetObject']);
});

test('the cost is what the document GROWS by, separator included', () => {
  // Still a subtraction and not a sum. Each policy pays for its own resource clause now - that is
  // what the partition costs - but the comma joining this policy's statements to the ones already
  // there is part of the growth too, and summing statement sizes misses it.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'B', intent: 'deny_only', actions: ['s3:PutObject'], resources: [BUCKET] },
  ];
  const view = policyContribution(restrictions, 'B', { accountId: '1' });
  assert.equal(view.total, inlineBytes(composeInline(restrictions, { accountId: '1' })));
  assert.equal(view.without,
               inlineBytes(composeInline(restrictions.slice(0, 1), { accountId: '1' })));
  assert.equal(view.share, view.total - view.without);
  // The bucket ARN is in this policy's own statement now, so the share carries it - and one byte
  // more than the statement alone, which is the separator.
  const alone = inlineBytes({ Version: '2012-10-17', Statement: [view.statements[0].statement] });
  const empty = inlineBytes({ Version: '2012-10-17', Statement: [] });
  assert.equal(view.share, alone - empty + 1, `${view.share} vs ${alone - empty} + 1`);
});

test('the fence is in neither byte figure and comes back on its own', () => {
  // It is composed from the assessment's grants, not from the restrictions, so it is the same with
  // or without this policy and cancels out of the subtraction. Returned separately because the
  // approver still has to see the statements their policy's PassRole grant earns.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
  ];
  const options = {
    accountId: '718100330247',
    fenceGrants: [{ ...LAMBDA_GRANT, services: ['ec2.amazonaws.com', 'lambda.amazonaws.com'] }],
    policyFenceServices: ['lambda.amazonaws.com'],
  };
  const view = policyContribution(restrictions, 'A', options);
  const fenceOnly = inlineBytes(composeInline([], options));
  // The fence is hundreds of bytes and none of them are in `share` - which is the claim. What IS in
  // it, exactly once, is the comma joining this statement to the ones already there: a marginal cost
  // is what the document grows by, and the separator is part of that growth. The subtraction gets
  // that right for free, and it is worth pinning because the obvious "sum the statements" answer
  // gets it wrong in the other direction.
  assert.ok(view.share < fenceOnly / 2, `${view.share} vs a fence of ${fenceOnly} - the fence is in the share`);
  const bare = policyContribution(restrictions, 'A', { accountId: '718100330247' });
  assert.equal(view.share, bare.share + 1,
               'the only difference the fence makes is the comma before this statement');

  assert.equal(view.fence.length, 1, 'the fence is not filtered to this policy');
  assert.equal(view.fence[0].Condition.StringEquals['iam:PassedToService'], 'lambda.amazonaws.com');
  // And it is not counted as one of the policy's own statements - its action is iam:PassRole, which
  // this policy did not choose.
  assert.ok(!view.statements.some((s) => s.statement.Sid.startsWith('PassRole')));
});

test('a policy that chose nothing contributes nothing, and says so with a zero', () => {
  // Not an error and not an empty document - the honest answer is that every statement in the
  // preview above came from somewhere else.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
  ];
  const view = policyContribution(restrictions, 'B', { accountId: '1' });
  assert.deepEqual(view.statements, []);
  assert.equal(view.share, 0);
  assert.equal(view.total, view.without);
});

test('an excerpt is not shaped like a document', () => {
  // A per-policy view rendered as {Version, Statement} would be a complete, valid, standalone IAM
  // policy that does not exist anywhere. The permission set has ONE inline document; four of these
  // side by side would be four things that do not exist in front of the one that does.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
  ];
  const view = policyContribution(restrictions, 'A', { accountId: '1' });
  const text = readableStatements(view.statements.map((s) => s.statement));
  assert.ok(text.trimStart().startsWith('['), 'the excerpt is an object, so it reads as a document');
  assert.ok(!text.includes('"Version"'), 'the excerpt carries a Version, so it is a document');
  // Same key order as the document, so the two can be read side by side.
  assert.ok(text.indexOf('"Sid"') < text.indexOf('"Effect"'));
  assert.ok(text.indexOf('"Effect"') < text.indexOf('"Action"'));
});

test('two policies that decide the SAME thing get one statement each', () => {
  // The failure this closes, from the other side. While the two folded into one statement, removing
  // either left it standing - so each approver saw a statement listed as their policy's, was told
  // it added nothing, and unticking it did not remove the Deny. Two statements now, and unticking
  // one removes one, which is what the screen has always implied.
  const restrictions = [
    { policy: 'AmazonS3FullAccess', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'DataTeamAccess', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
  ];
  const whole = composeInline(restrictions, { accountId: '1' });
  assert.equal(whole.Statement.length, 2, 'they folded together, which no Sid could name');

  for (const policy of ['AmazonS3FullAccess', 'DataTeamAccess']) {
    const view = policyContribution(restrictions, policy, { accountId: '1' });
    assert.equal(view.statements.length, 1, policy);
    assert.deepEqual(view.statements[0].ours, ['s3:GetObject'], policy);
    assert.equal(view.statements[0].statement.Sid, `${denySidBase(policy)}1`, policy);
    // And the marginal cost is no longer zero: it is this policy's own copy of the clause, which is
    // exactly what unticking here removes.
    assert.ok(view.share > BUCKET.length, `${policy}: ${view.share}`);
  }
});

test("a neighbour's actions never appear in this policy's excerpt", () => {
  // What the co-ownership machinery existed to explain, and what the partition removes instead: B's
  // four actions used to ride in the same statement as A's one, so A's view had to show them and
  // say where they came from - and a count of them was once rendered as "shared with 4 policies" on
  // a permission set with two. Now they are B's statement and A never sees them.
  const restrictions = [
    { policy: 'A', intent: 'deny_only', actions: ['s3:GetObject'], resources: [BUCKET] },
    { policy: 'B', intent: 'deny_only', resources: [BUCKET],
      actions: ['s3:PutObject', 's3:DeleteObject', 's3:ListBucket', 's3:RestoreObject'] },
  ];
  const view = policyContribution(restrictions, 'A', { accountId: '1' });
  assert.equal(view.statements.length, 1);
  assert.deepEqual(view.statements[0].ours, ['s3:GetObject']);
  assert.equal(view.statements[0].statement.Action, 's3:GetObject');
});

test('a falsy fence service cannot select a statement that is not a fence', () => {
  // Optional chaining yields undefined for a statement with no Condition, and undefined is a legal
  // Set member - so one undefined in the caller's list selected every admin Deny in the document
  // and rendered it under "the pipeline adds this fence", excluded from the byte figure and shown
  // twice.
  const restrictions = [
    { policy: 'A', intent: 'deny_action', actions: ['s3:CreateBucket'] },
    { policy: 'A', intent: 'tag_condition', actions: ['s3:GetObject'],
      tag_key: 'env', tag_values: ['prod'] },
  ];
  const view = policyContribution(restrictions, 'A', {
    accountId: '1',
    fenceGrants: [LAMBDA_GRANT],
    policyFenceServices: [undefined, '', null],
  });
  assert.deepEqual(view.fence, [], 'a falsy entry selected statements that are not fences');
  // The real thing still works beside it.
  const real = policyContribution(restrictions, 'A', {
    accountId: '1',
    fenceGrants: [LAMBDA_GRANT],
    policyFenceServices: [undefined, 'lambda.amazonaws.com'],
  });
  assert.equal(real.fence.length, 1);
  assert.equal(real.fence[0].Sid, 'ampLambdaFullAccessFence');
});

// ---- what the call CREATES is exempted, or the statement is a total deny in disguise ------------

const ENI_SG = 'arn:aws:ec2:us-east-1:718100330247:security-group/sg-0bba3f2419bc5ac3c';
const ENI_SUBNET = 'arn:aws:ec2:us-east-1:718100330247:subnet/subnet-01ad3a906cdcdbc82';
const ENI_PATTERN = 'arn:${Partition}:ec2:*:${Account}:network-interface/*';

test('allow_only on a creating action exempts the created type, substituted from the picked ARNs', () => {
  // The reported defect. IAM authorises ec2:CreateNetworkInterface against the subnet, the groups
  // AND the interface being created; the interface's ARN exists only after the call succeeds, so
  // it is in no list, and without the exemption the Deny matches it on every call - the statement
  // the screen read as "only into this subnet, only with this group" denied every create.
  const doc = composeInline(
    [{ policy: 'p', intent: 'allow_only', actions: ['ec2:CreateNetworkInterface'],
       resources: [ENI_SG, ENI_SUBNET] }],
    { accountId: '718100330247', createdFormats: () => [ENI_PATTERN] },
  );
  assert.deepEqual(doc.Statement[0].NotResource, [
    'arn:aws:ec2:*:718100330247:network-interface/*',
    ENI_SG,
    ENI_SUBNET,
  ]);
});

test('deny_only on the same action gets no exemption', () => {
  // Its Resource list bites ON the named existing resources and the created one is simply not
  // listed. Adding the type pattern there would deny every create outright - a different decision,
  // with a name: deny_action.
  const doc = composeInline(
    [{ policy: 'p', intent: 'deny_only', actions: ['ec2:CreateNetworkInterface'],
       resources: [ENI_SUBNET] }],
    { accountId: '718100330247', createdFormats: () => [ENI_PATTERN] },
  );
  assert.deepEqual(doc.Statement[0].Resource, [ENI_SUBNET]);
  assert.ok(!('NotResource' in doc.Statement[0]));
});

test('an empty account slot stays empty and a needed one comes from the picked ARNs', () => {
  // ec2 image ARNs carry NO account - arn:aws:ec2:region::image/ami-x - and substituting one in
  // composes a pattern that matches nothing, which is the same total deny wearing the fix's name.
  assert.equal(creationExemption('arn:${Partition}:ec2:*::image/*', [ENI_SUBNET]),
               'arn:aws:ec2:*::image/*');
  assert.equal(creationExemption(ENI_PATTERN, [ENI_SUBNET]),
               'arn:aws:ec2:*:718100330247:network-interface/*');
  // Deterministic whatever order the page sent the list in: the first SORTED ARN answers.
  assert.equal(creationExemption(ENI_PATTERN, [ENI_SUBNET, ENI_SG]),
               creationExemption(ENI_PATTERN, [ENI_SG, ENI_SUBNET]));
  // And null - not an empty-account pattern - when nothing picked carries an account. The writer
  // refuses that decision; a pattern with an empty account would silently reinstate the bug.
  assert.equal(creationExemption(ENI_PATTERN, ['arn:aws:s3:::bucket-only']), null);
});

test('the per-policy excerpt still finds the statement that carries an exemption', () => {
  // Attribution rebuilds each decision's clause with the same statement() the fold uses. A key
  // built WITHOUT createdFormats would never match the composed statement - the exemption is inside
  // the clause bytes - and the policy's own decision would drop out of its excerpt.
  const restrictions = [
    { policy: 'A', intent: 'allow_only', actions: ['ec2:CreateNetworkInterface'],
      resources: [ENI_SUBNET] },
    { policy: 'B', intent: 'deny_only', actions: ['s3:GetObject'], resources: ['arn:aws:s3:::b'] },
  ];
  const options = { accountId: '718100330247', createdFormats:
    (action) => (action === 'ec2:CreateNetworkInterface' ? [ENI_PATTERN] : []) };
  const view = policyContribution(restrictions, 'A', options);
  assert.equal(view.statements.length, 1, "A's own creating decision fell out of its excerpt");
  assert.deepEqual(view.statements[0].ours, ['ec2:CreateNetworkInterface']);
  assert.ok(view.statements[0].statement.NotResource
    .includes('arn:aws:ec2:*:718100330247:network-interface/*'));
});

test('the fixtures actually exercise the exemption, in both intents', () => {
  // A fixture set with no creating allow_only case would pass while the JavaScript never exempted
  // anything - the same blind spot the nested fixtures guard against.
  assert.ok(FIXTURES.cases.some((c) => Object.keys(c.created_formats ?? {}).length > 0
                                       && c.restrictions.some((r) => r.intent === 'allow_only')),
            'no fixture covers a creating action under allow_only');
  assert.ok(FIXTURES.cases.some((c) => Object.keys(c.created_formats ?? {}).length > 0
                                       && c.restrictions.some((r) => r.intent === 'deny_only')),
            'no fixture pins that deny_only gets no exemption');
});

// ---- key_condition: deny by a declared request condition key ------------------------------------

test('an absent condition operator composes as the default the writer parses', () => {
  // restriction.from_dict fills StringNotEquals in AT PARSE, so a stored decision without the field
  // IS a StringNotEquals decision - there is no third state. The preview applies the same default
  // in statement(), or the same stored row composes different bytes in the two languages.
  const stored = { policy: 'p', intent: 'key_condition',
                   actions: ['lambda:CreateFunctionUrlConfig'],
                   condition_key: 'lambda:FunctionUrlAuthType', condition_values: ['AWS_IAM'] };
  const doc = composeInline([stored], { accountId: '1' });
  assert.equal(doc.Statement[0].Resource, '*');
  assert.deepEqual(doc.Statement[0].Condition,
                   { StringNotEquals: { 'lambda:FunctionUrlAuthType': ['AWS_IAM'] } });
  assert.equal(serialise(doc),
               serialise(composeInline([{ ...stored, condition_operator: 'StringNotEquals' }],
                                       { accountId: '1' })),
               'the absent operator and the explicit default compose different bytes');
});

test('a tag condition reads its operator, and an absent one keeps the OLD meaning', () => {
  // The fix and its compatibility rule in one test. The branch hardcoded StringEquals, so every
  // tag restriction ever written read as the open form - a resource with no Environment tag does
  // not match StringEquals, the Deny does not fire, and the untagged resource walks past. The
  // closed form denies exactly that resource. But an absent operator on a STORED decision is not
  // "unspecified": it composed StringEquals when it was approved, and must keep doing so.
  const row = (over) => ({ policy: 'p', intent: 'tag_condition', actions: ['s3:DeleteObject'],
                           tag_key: 'Environment', tag_values: ['production'], ...over });
  const conditionOf = (r) => composeInline([r], { accountId: '1' }).Statement[0].Condition;
  assert.deepEqual(conditionOf(row({ condition_operator: 'StringNotEquals' })),
                   { StringNotEquals: { 'aws:ResourceTag/Environment': ['production'] } });
  assert.deepEqual(conditionOf(row({})),
                   { StringEquals: { 'aws:ResourceTag/Environment': ['production'] } },
                   'an absent operator flipped a stored tag decision to the closed form');
  // The two condition intents' absences mean DIFFERENT things, and that asymmetry is the point.
  assert.deepEqual(
    composeInline([{ policy: 'p', intent: 'key_condition', actions: ['lambda:CreateFunctionUrlConfig'],
                     condition_key: 'lambda:FunctionUrlAuthType', condition_values: ['AWS_IAM'] }],
                  { accountId: '1' }).Statement[0].Condition,
    { StringNotEquals: { 'lambda:FunctionUrlAuthType': ['AWS_IAM'] } },
  );
});

test('the fixtures pin both tag spellings, including the absent one', () => {
  const rows = FIXTURES.cases.flatMap((c) => c.restrictions ?? [])
    .filter((r) => r.intent === 'tag_condition');
  assert.ok(rows.some((r) => r.condition_operator === 'StringNotEquals'),
            'no fixture covers the closed tag form the fix exists for');
  assert.ok(rows.some((r) => !r.condition_operator),
            'no fixture pins that an old tag decision keeps composing the open form');
});

test('the fixtures actually exercise the condition intent, default and chosen', () => {
  // Deleting the key_condition branch from statement() must fail the parity test, which it can only
  // do while the fixture set still carries the cases - and the default-absent one is the load-
  // bearing one, because it is the only place the two languages' parse defaults meet.
  const rows = FIXTURES.cases.flatMap((c) => c.restrictions ?? [])
    .filter((r) => r.intent === 'key_condition');
  assert.ok(rows.some((r) => !r.condition_operator),
            'no fixture pins the parse default (operator absent on the wire)');
  assert.ok(rows.some((r) => r.condition_operator === 'StringEquals'),
            'no fixture covers the explicitly chosen open operator');
  assert.ok(rows.some((r) => (r.condition_values ?? []).length > 1),
            'no fixture makes the value sort observable');
});
