// The inline policy an administrator's choices will become, composed here so they can read it.
//
// NOT the authority. The container recomposes from the decisions and refuses what it will not
// write, and that is deliberate - a web tier that authors IAM content is a web tier that can grant,
// which is why decisions cross the wire and not documents. What this is for is the question the
// page could not answer before: "I ticked eleven actions across four policies; what did I just
// write?" An approver who cannot see that is approving a description of a document rather than the
// document.
//
// So it has one hard requirement: it must produce the SAME BYTES as
// event_pipeline/code/generator/restriction.py for the same decisions. A preview that differs from
// what gets written is worse than no preview - it is a wrong answer with a screenshot. That is not
// left to care: inlinePreview.test.js pins this output against fixtures generated by the Python,
// and the two drift apart as a test failure rather than in production.
//
// Plain JS with a .d.ts beside it, same arrangement as arn.js and consoleLinks.js, and for the same
// reason: node --test is the one test runner here and it cannot load TypeScript.

/** The permission set inline policy quota - the 10,240 one, not the 32,768 the API accepts. */
export const INLINE_LIMIT = 10240;

/** Statement identifiers the administrator's restriction owns. The writer replaces these by prefix. */
const ADMIN_DENY_SID = 'AdminDeny';
// Every fence Sid ends with this, and the name before it says which ATTACHMENT opened the hole:
// ampLambdaFullAccessFence for AWSLambda_FullAccess, cmpTestpolicyFence for cmp-testpolicy. It used
// to be PassRoleAllowlistFence<n>, numbered over the services, which named no attachment at all.
// Byte-identical with generator/restriction.py fence_sid() - see the note at the top of this file.
const PASSROLE_FENCE_SUFFIX = 'Fence';
const FENCE_SID_STRIP = /[^0-9A-Za-z]+/g;

// What a name loses to the origin that already says it. mirror-cmp-* is what a permission set
// actually references - never the cmp-* spec behind it - so both spell one policy one way.
const TWIN_POLICY_PREFIX = 'mirror-cmp-';
const SPEC_POLICY_PREFIX = 'cmp-';

/** How much of a policy name a restriction's Sid carries. config.sid_policy_name_limit. */
const SID_POLICY_NAME_LIMIT = 24;

/**
 * (origin, Name) for a Sid that has to say WHICH attached policy a statement belongs to.
 *
 * Byte-identical with restriction._policy_token, and shared by the two families that name a policy
 * for the same reason it is there: a document holds both, and a reader should not have to learn two
 * spellings of one policy's name.
 */
function policyToken(identifier, source) {
  const name = String(identifier ?? '').trim();
  const bare = name.includes('/') ? name.slice(name.lastIndexOf('/') + 1) : name;
  // source is the authority; the ARN answers when it is absent, because an AWS managed policy filed
  // under cmp would carry the wrong origin AND the AWS the prefix exists to absorb.
  const known = (source === 'aws_managed' || source === 'customer_managed')
    ? source
    : (name.includes('::aws:policy/') ? 'aws_managed' : 'customer_managed');
  const origin = known === 'aws_managed' ? 'amp' : 'cmp';
  const redundant = origin === 'amp' ? ['aws'] : [TWIN_POLICY_PREFIX, SPEC_POLICY_PREFIX];
  let trimmed = bare;
  for (const prefix of redundant) {
    if (bare.toLowerCase().startsWith(prefix.toLowerCase())) {
      trimmed = bare.slice(prefix.length);
      break;
    }
  }
  let stripped = trimmed.replace(FENCE_SID_STRIP, '');
  if (/^[A-Za-z]/.test(stripped)) stripped = stripped[0].toUpperCase() + stripped.slice(1);
  return [origin, stripped];
}

/** The Sid an attachment's fence carries: [amp|cmp]<PolicyName>Fence. Never cut to length. */
export function fenceSid(identifier, source) {
  const [origin, name] = policyToken(identifier, source);
  return `${origin}${name || 'Unnamed'}${PASSROLE_FENCE_SUFFIX}`;
}

/**
 * AdminDeny<Amp|Cmp><PolicyName>, the family every statement from one attached policy shares.
 *
 * The number that follows counts within THIS policy's group, so it does not move when another
 * policy gains or loses a statement. What it replaces is AdminDeny<n> over the whole fold, which
 * named no attachment at all - survivable while one inline document held everything and one writer
 * replaced it wholesale, and not survivable once the family spans several customer managed
 * policies and a per-document number means two documents both start at one.
 */
export function denySidBase(identifier, source) {
  const [origin, name] = policyToken(identifier, source);
  const cut = name.slice(0, SID_POLICY_NAME_LIMIT);
  return `${ADMIN_DENY_SID}${origin[0].toUpperCase()}${origin.slice(1)}${cut || 'Unnamed'}`;
}

/**
 * The bytes the API sees, and the bytes the quota counts.
 *
 * Keys sorted and no whitespace, which is `json.dumps(sort_keys=True, separators=(',', ':'))` in
 * restriction.py. Both halves matter: the separators are why the size check is against the
 * non-whitespace quota without having to strip anything, and the sort is why two processes
 * composing the same decisions produce the same digest.
 */
export function serialise(value) {
  if (Array.isArray(value)) return `[${value.map(serialise).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort()
      .map((k) => `${JSON.stringify(k)}:${serialise(value[k])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

/**
 * The pattern naming everything UNDER an ARN. Mirrors restriction.sub_resource.
 *
 * An index holds containers - Resource Explorer reports a bucket and never an object - so the ARN
 * picked for s3:GetObject is the bucket, and arn:aws:s3:::b does not match arn:aws:s3:::b/key.
 *
 * The separator is whichever of ':' or '/' comes FIRST in the resource section, because that is the
 * one following the resource TYPE and a later one belongs to the name. Taking the last separator is
 * the version that looks right and gets arn:aws:logs:…:log-group:/aws/lambda/x wrong.
 */
export function subResource(arn) {
  const head = String(arn).split(':');
  const tail = head.length > 5 ? head.slice(5).join(':') : '';
  const slash = tail.indexOf('/');
  const colon = tail.indexOf(':');
  return (colon >= 0 && (slash < 0 || colon < slash)) ? `${arn}:*` : `${arn}/*`;
}

/**
 * The ARNs one action's statement lists. Mirrors restriction._resources.
 *
 * `nested` answers what generator/actions.Table.under_another_type answers on the writing side:
 * does this action operate BELOW the resource an index can hold. Impact.tsx builds it from the
 * assessment's action_reference, which carries nested_types for exactly this.
 *
 * Only when it does. ssm has no child type, and appending /* to a parameter ARN would put every
 * parameter below it in the same list - under allow_only, a permission nobody granted.
 */
function resourcesFor(restriction, action, nested) {
  const picked = [...(restriction.resources ?? [])].sort();
  if (picked.length === 0 || !nested(action)) return picked;
  return [...new Set([...picked, ...picked.map(subResource)])].sort();
}

/**
 * One creation-exemption pattern, made concrete. Mirrors restriction.substitute_exemption.
 *
 * ${Partition} takes the first sorted picked ARN's partition, ${Account} the first non-empty
 * account among them - and null when no picked ARN carries one, because an empty account composes
 * a pattern that matches nothing and silently reinstates the total deny the exemption exists to
 * prevent. The writer REFUSES that decision (restriction._validate); the preview drops the pattern,
 * which only ever differs from the writer on a decision the writer will not accept.
 */
export function creationExemption(pattern, picked) {
  const arns = [...(picked ?? [])].map(String).sort();
  let out = pattern.split('${Partition}').join(arns.length ? arns[0].split(':')[1] ?? '' : 'aws');
  if (out.includes('${Account}')) {
    const account = arns.map((a) => a.split(':')[4]).find(Boolean);
    if (!account) return null;
    out = out.split('${Account}').join(account);
  }
  return out;
}

/**
 * What an absent condition operator MEANS, per intent. Mirrors restriction.DEFAULT_CONDITION_OPERATOR.
 *
 * The two answers differ, and it is about records rather than taste. key_condition was born closed,
 * so absence normalises to the form the design chose. tag_condition was born OPEN - its branch
 * hardcoded StringEquals until the operator existed - so an absent operator on one of those stored
 * decisions is not "unspecified", it IS StringEquals, and reading it as the closed form would
 * silently invert a control somebody already approved. The editor proposes the closed form for a
 * NEW tag decision; that is a different thing from what an unmarked old record means.
 */
const DEFAULT_CONDITION_OPERATOR = {
  key_condition: 'StringNotEquals',
  tag_condition: 'StringEquals',
};

const conditionOperator = (restriction) =>
  restriction.condition_operator ?? DEFAULT_CONDITION_OPERATOR[restriction.intent];

/**
 * One action, one statement - before the fold. Mirrors restriction._statement.
 *
 * `createdFor` answers what generator/actions.Table.creation_exemptions answers on the writing
 * side: the patterns naming the whole of every type this action brings into being. IAM authorises
 * a multi-resource call against EVERY resource in the request, including the one being created -
 * so an allow_only NotResource scoped to the picked subnet and security group still matches the
 * network interface the call creates, whose ARN nobody has yet, and denies every call while
 * reading as a scope. The exemption is what lets the Deny bite only through the resources the
 * administrator actually chose. The reference carries the patterns as created_formats; an
 * assessment written before it did means no exemption here, and the writer refuses or writes
 * wider than this preview shows - the runbook's re-query step is what closes that window.
 */
function statement(sid, restriction, action, nested, createdFor = () => []) {
  const base = { Sid: sid, Effect: 'Deny', Action: action };
  if (restriction.intent === 'deny_action') {
    // No resource clause to compose. Byte-identical to the flat Deny an unscopable action gets
    // under deny_only with no resources, so the two fold into one statement.
    return { ...base, Resource: '*' };
  }
  if (restriction.intent === 'tag_condition') {
    return {
      ...base,
      Resource: '*',
      Condition: {
        [conditionOperator(restriction)]: {
          [`aws:ResourceTag/${restriction.tag_key ?? ''}`]: [...(restriction.tag_values ?? [])].sort(),
        },
      },
    };
  }
  if (restriction.intent === 'key_condition') {
    return {
      ...base,
      Resource: '*',
      Condition: {
        [conditionOperator(restriction)]: {
          [restriction.condition_key ?? '']: [...(restriction.condition_values ?? [])].sort(),
        },
      },
    };
  }
  const resources = resourcesFor(restriction, action, nested);
  if (restriction.intent === 'allow_only') {
    // The complement: what is KEPT is listed, so anything not listed - including whatever is
    // created after this is written - is denied. Plus the exemption for whatever THIS CALL
    // creates. deny_only below deliberately gets none: its Resource list bites ON the named
    // existing resources, and adding the type pattern there would deny every create outright -
    // a different decision, with a name (deny_action).
    const exempt = (createdFor(action) ?? [])
      .map((pattern) => creationExemption(pattern, restriction.resources ?? []))
      .filter(Boolean);
    return { ...base, NotResource: [...new Set([...resources, ...exempt])].sort() };
  }
  // No resources means the flat deny the container permits for account-level actions only.
  return { ...base, Resource: resources.length ? resources : '*' };
}

/** Everything about a statement except which action it is about. The fold's grouping key. */
function clause(built) {
  const rest = { ...built };
  delete rest.Sid;
  delete rest.Action;
  return serialise(rest);
}

/**
 * Actions whose statement is otherwise byte-identical, collected into one Action list.
 *
 * ONE POLICY'S statements. The caller groups by attached policy first and this folds inside a
 * group, so a statement belongs to exactly one policy and `base` can name it - see denySidBase.
 *
 * Mirrors restriction._fold, including the two details that are easy to drop and would show up as
 * different bytes: groups come out sorted by clause, and a lone action stays a string rather than
 * becoming a one-element array.
 */
function fold(built, base = ADMIN_DENY_SID) {
  const groups = new Map();
  for (const one of built) {
    const key = clause(one);
    const names = Array.isArray(one.Action) ? one.Action : [one.Action];
    const set = groups.get(key) ?? new Set();
    for (const name of names) set.add(name);
    groups.set(key, set);
  }
  return [...groups.keys()].sort().map((key, index) => {
    const names = [...groups.get(key)].sort();
    return {
      Sid: `${base}${index + 1}`,
      Action: names.length === 1 ? names[0] : names,
      ...JSON.parse(key),
    };
  });
}

/**
 * Every restriction's statements, grouped by the attached policy and folded inside each group.
 *
 * Mirrors restriction.statements' grouping. The order is by Sid base rather than by identifier so
 * the document reads the way a person scans it, and two policies whose names reduce to one base
 * are a REFUSAL in the container - the preview does not refuse, it composes what the container
 * would and lets the container be the one that says no.
 */
function foldByPolicy(builtByPolicy) {
  const bases = new Map();
  for (const identifier of builtByPolicy.keys()) bases.set(denySidBase(identifier), identifier);
  const out = [];
  for (const base of [...bases.keys()].sort()) {
    out.push(...fold(builtByPolicy.get(bases.get(base)), base));
  }
  return out;
}

/**
 * The PassRole fence, as the writer will compose it.
 *
 * Shown because it is in the same document and spends the same quota, and because an approver
 * reading the policy should not find a statement in the deployed version that the preview did not
 * have. The exemption list here is the placeholder alone - approved mirror ARNs are added by the
 * grant flow and widen it, which is one reason the size is an estimate and the writer measures.
 */
export function fenceStatements(grants, accountId) {
  // One statement per (attachment, service), keyed by the Sid the attachment implies - the same
  // shape passrole_fence() composes. Per service and not per attachment because the writer's
  // NotResource is per service, so folding two services into one statement would let a role
  // approved for one be passed to the other.
  const pairs = new Set();
  for (const grant of grants ?? []) {
    if (!grant || grant.unconditioned) continue;
    const sid = fenceSid(grant.identifier, grant.source);
    for (const service of grant.services ?? []) {
      const text = String(service ?? '').trim();
      if (text) pairs.add(`${sid}\u0000${text}`);
    }
  }

  const bySid = new Map();
  for (const pair of [...pairs].sort()) {
    const [sid, service] = pair.split('\u0000');
    if (!bySid.has(sid)) bySid.set(sid, []);
    bySid.get(sid).push(service);
  }

  const out = [];
  for (const sid of [...bySid.keys()].sort()) {
    const services = bySid.get(sid);
    services.forEach((service, index) => {
      out.push({
        // Numbered only where one attachment grants to more than one service. The ordinary policy
        // names one and its statement is ampLambdaFullAccessFence with nothing after it.
        Sid: services.length === 1 ? sid : `${sid}${index + 1}`,
        Effect: 'Deny',
        Action: 'iam:PassRole',
        NotResource: [`arn:aws:iam::${accountId}:role/mirror-denyrole`],
        Condition: { StringEquals: { 'iam:PassedToService': service } },
      });
    });
  }
  return out;
}

/**
 * The whole document, across every policy the administrator touched.
 *
 * Across every policy deliberately. The editor is per policy, but the permission set has ONE inline
 * document and a Deny in it applies whatever policy prompted it - so a per-policy preview would
 * show four documents that do not exist and hide the one that does, including how the four together
 * spend a single 10,240 character quota.
 */
export function composeInline(restrictions,
                              { accountId, fenceGrants = [], nested = () => false,
                                createdFormats = () => [] } = {}) {
  const built = new Map();
  for (const restriction of restrictions ?? []) {
    for (const action of restriction.actions ?? []) {
      const mine = built.get(restriction.policy) ?? [];
      mine.push(statement(ADMIN_DENY_SID, restriction, action, nested, createdFormats));
      built.set(restriction.policy, mine);
    }
  }
  return {
    Version: '2012-10-17',
    Statement: [...foldByPolicy(built), ...fenceStatements(fenceGrants, accountId)],
  };
}

/** What the document will cost against the quota. */
export function inlineBytes(document) {
  return new TextEncoder().encode(serialise(document)).length;
}

const READ_ORDER = ['Sid', 'Effect', 'Action', 'NotAction', 'Resource', 'NotResource', 'Condition'];

const ordered = (one) => Object.fromEntries(
  Object.keys(one)
    .sort((a, b) => (READ_ORDER.indexOf(a) + 1 || 99) - (READ_ORDER.indexOf(b) + 1 || 99))
    .map((k) => [k, one[k]]),
);

/** The document as a person reads it - indented, keys in the order IAM documents are written. */
export function readable(document) {
  return JSON.stringify({
    Version: document.Version,
    Statement: document.Statement.map(ordered),
  }, null, 2);
}

/**
 * An EXCERPT of a document - statements alone, no Version.
 *
 * Deliberately not document-shaped. A per-policy view rendered with readable() would be a complete,
 * valid, well-formed IAM policy that does not exist anywhere, and an approver who screenshots it has
 * a wrong answer with a screenshot. A bare array cannot be mistaken for the thing that gets written.
 */
export function readableStatements(statements) {
  return JSON.stringify((statements ?? []).map(ordered), null, 2);
}

/**
 * What ONE attached policy puts into the shared document.
 *
 * The permission set has one inline document and every Deny in it applies whatever policy prompted
 * it - which is why composeInline runs across every policy and why a per-policy DOCUMENT would be a
 * lie. This is not that. It composes the whole document once and then reads this policy's
 * contribution back out of it, so every Sid shown is the Sid that will be written.
 *
 * Attribution is by SID FAMILY, because that is now what ownership is. The fold runs inside one
 * attached policy's group, so every statement carries the Sid base its policy implies and no
 * statement has two owners. Matching on `^<base>\d+$` rather than on the base as a prefix: bases
 * are alphanumeric and one can begin another (AdminDenyCmpWeb and AdminDenyCmpWebHosting), and the
 * anchored digits are what keeps the shorter one from claiming the longer one's statements.
 *
 * It used to match on the composed CLAUSE, because the fold grouped by clause across every policy
 * and a statement could carry two policies' actions. That is gone, and with it three things this
 * had to explain: gaps in the Sid numbering, statements listed in two excerpts at once, and a
 * marginal cost of zero for a decision another policy had already paid for. Two policies that
 * decide the identical thing now compose two statements, each named for its own policy.
 *
 * What does NOT change is that `share` is MARGINAL - what the document grows by because of this
 * policy, not the sum of the bytes of the statements above. The separator that joins this policy's
 * statements to the ones already there is part of that growth, and the subtraction gets it right
 * where summing statement sizes does not.
 *
 * The PassRole fence is in neither figure: it is composed from the assessment's grants and is the
 * same with or without this policy's restrictions, so it cancels out of the subtraction. It is
 * returned separately, filtered to the services THIS policy's grant names.
 */
export function policyContribution(restrictions, policy, options = {}) {
  const all = (restrictions ?? []).filter((r) => (r.actions ?? []).length > 0);
  const document = composeInline(all, options);
  const without = composeInline(all.filter((r) => r.policy !== policy), options);

  const mine = new RegExp(`^${denySidBase(policy)}\\d+$`);
  const statements = [];
  for (const one of document.Statement) {
    if (!mine.test(one.Sid ?? '')) continue;
    const names = Array.isArray(one.Action) ? one.Action : [one.Action];
    statements.push({ statement: one, ours: names });
  }

  // Falsy entries dropped, and the statement's own value checked for truthiness before the lookup.
  // Optional chaining yields undefined for a statement with no Condition, and undefined is a legal
  // Set member - so one undefined in the caller's list would select every admin Deny in the
  // document and render it under "the pipeline adds this fence".
  const fenced = new Set((options.policyFenceServices ?? []).filter(Boolean));
  const fence = document.Statement.filter((one) => {
    const service = one.Condition?.StringEquals?.['iam:PassedToService'];
    return Boolean(service) && fenced.has(service);
  });

  const total = inlineBytes(document);
  return {
    statements,
    fence,
    total,
    without: inlineBytes(without),
    share: total - inlineBytes(without),
  };
}
