// That the preview and the writer produce the same bytes.
//
// The page now shows an administrator the inline policy their choices will become. That is only
// worth having if it is the policy that actually gets written - a preview that differs from the
// deployed document is a wrong answer with a screenshot, and worse than no preview at all, because
// somebody approves against it.
//
// The authority is event_pipeline/code/generator/restriction.py. It is Python and this is Node, so
// they cannot share the code; what they share instead is fixtures. server/fixtures/inline-preview.json
// is generated BY the Python from a set of decisions, carrying the exact bytes it composed, and
// every case here re-composes the same decisions in JavaScript and demands the same string.
//
// Regenerate after changing restriction.py:
//
//     cd event_pipeline && python3 - <<'EOF' > ../resource-dashboard/server/fixtures/inline-preview.json
//     ... see the header of that file
//     EOF
//
//     npm run check
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { INLINE_LIMIT, composeInline, inlineBytes, readable, serialise } from './inlinePreview.js';

const FIXTURES = JSON.parse(
  readFileSync(new URL('./fixtures/inline-preview.json', import.meta.url), 'utf8'),
);

test('every fixture composes to the bytes the container composed', () => {
  for (const c of FIXTURES.cases) {
    const document = composeInline(c.restrictions, {
      accountId: c.account_id ?? FIXTURES.account_id,
      fenceServices: c.fence_services ?? [],
    });
    assert.equal(serialise(document), c.serialised,
                 `${c.label}: the preview and generator/restriction.py disagree`);
    assert.equal(inlineBytes(document), c.bytes, `${c.label}: byte count`);
  }
});

test('the fixtures actually cover the fold, in both directions', () => {
  // A fixture set that only had foldable cases would pass while the JS folded everything.
  const folded = FIXTURES.cases.find((c) => c.label.includes('접힌다'));
  const kept = FIXTURES.cases.find((c) => c.label.includes('접히지 않는다'));
  assert.ok(folded && kept, 'the fixtures no longer pin both sides of the fold');
  assert.equal(composeInline(folded.restrictions, { accountId: FIXTURES.account_id })
    .Statement.length, 1);
  assert.equal(composeInline(kept.restrictions, { accountId: FIXTURES.account_id })
    .Statement.length, 2, 'two different resource lists were folded into one');
});

test('the serialiser sorts keys and emits no whitespace', () => {
  // Both halves are load-bearing. No whitespace is why the byte count can be compared to a
  // NON-whitespace quota without stripping anything; sorted keys are why two processes composing
  // the same decisions get the same digest.
  assert.equal(serialise({ b: 1, a: [3, 2] }), '{"a":[3,2],"b":1}');
  assert.ok(!/\s/.test(serialise({ Statement: [{ Sid: 'x', Effect: 'Deny' }] })));
});

test('one action stays a string and two become a sorted array', () => {
  const one = composeInline([{ intent: 'allow_only', actions: ['s3:PutObject'],
                              resources: ['arn:aws:s3:::b'] }], { accountId: '1' });
  assert.equal(one.Statement[0].Action, 's3:PutObject');
  const two = composeInline([{ intent: 'allow_only', actions: ['s3:PutObject', 's3:DeleteObject'],
                              resources: ['arn:aws:s3:::b'] }], { accountId: '1' });
  assert.deepEqual(two.Statement[0].Action, ['s3:DeleteObject', 's3:PutObject']);
});

test('the order the administrator ticked things in does not change the document', () => {
  // Otherwise the same restriction reads as a change every time it is re-opened, and a terraform
  // plan over an unchanged one has a diff in it.
  const a = [{ intent: 'allow_only', actions: ['s3:PutObject'], resources: ['arn:aws:s3:::z', 'arn:aws:s3:::a'] },
             { intent: 'allow_only', actions: ['s3:GetObject'], resources: ['arn:aws:s3:::a'] }];
  assert.equal(serialise(composeInline(a, { accountId: '1' })),
               serialise(composeInline([...a].reverse(), { accountId: '1' })));
});

test('the fence is in the document, because it spends the same quota', () => {
  // An approver who reads the preview must not find a statement in the deployed version that the
  // preview did not have - and the fence is the one the pipeline adds on its own.
  const withFence = composeInline([], { accountId: '718100330247',
                                        fenceServices: ['lambda.amazonaws.com'] });
  assert.equal(withFence.Statement.length, 1);
  assert.match(withFence.Statement[0].Sid, /^PassRoleAllowlistFence/);
  assert.equal(composeInline([], { accountId: '1' }).Statement.length, 0);
});

test('the fold is what keeps a wide restriction under the quota', () => {
  // The reason it exists. Twenty actions over forty kept ARNs wrote those ARNs twenty times.
  const resources = Array.from({ length: 40 }, (_, i) => `arn:aws:s3:::bucket-${String(i).padStart(3, '0')}`);
  const restrictions = Array.from({ length: 20 }, (_, i) => ({
    intent: 'allow_only', actions: [`s3:Action${String(i).padStart(2, '0')}`], resources,
  }));
  const document = composeInline(restrictions, { accountId: '1' });
  assert.equal(document.Statement.length, 1);
  assert.ok(inlineBytes(document) < INLINE_LIMIT, `${inlineBytes(document)} bytes`);
});

test('what a person reads is indented and in the order a policy is written', () => {
  // The bytes above are for the quota and the digest. This is the one an approver looks at, and
  // Sid-Effect-Action-Resource is the order every IAM document in the world is written in.
  const text = readable(composeInline(
    [{ intent: 'allow_only', actions: ['s3:PutObject'], resources: ['arn:aws:s3:::b'] }],
    { accountId: '1' },
  ));
  assert.ok(text.includes('\n  '), 'the readable form is not indented');
  const first = text.indexOf('"Sid"');
  assert.ok(first < text.indexOf('"Effect"'));
  assert.ok(text.indexOf('"Effect"') < text.indexOf('"Action"'));
  assert.ok(text.indexOf('"Action"') < text.indexOf('"NotResource"'));
});
