// The inline policy an administrator's choices will become, composed here so they can read it.
//
// NOT the authority. The container recomposes from the decisions and refuses what it will not
// write, and that is deliberate - a web tier that authors IAM content is a web tier that can grant,
// which is why decisions cross the wire and not documents. What this is for is the question the
// page could not answer before: "I ticked eleven actions across four policies; what did I just
// write?" An approver who cannot see that is approving a description of a document rather than the
// document.
//
// So it has one hard requirement: it must produce the SAME BYTES as
// event_pipeline/code/generator/restriction.py for the same decisions. A preview that differs from
// what gets written is worse than no preview - it is a wrong answer with a screenshot. That is not
// left to care: inlinePreview.test.js pins this output against fixtures generated by the Python,
// and the two drift apart as a test failure rather than in production.
//
// Plain JS with a .d.ts beside it, same arrangement as arn.js and consoleLinks.js, and for the same
// reason: node --test is the one test runner here and it cannot load TypeScript.

/** The permission set inline policy quota - the 10,240 one, not the 32,768 the API accepts. */
export const INLINE_LIMIT = 10240;

/** Statement identifiers the administrator's restriction owns. The writer replaces these by prefix. */
const ADMIN_DENY_SID = 'AdminDeny';
const PASSROLE_FENCE_SID = 'PassRoleAllowlistFence';

/**
 * The bytes the API sees, and the bytes the quota counts.
 *
 * Keys sorted and no whitespace, which is `json.dumps(sort_keys=True, separators=(',', ':'))` in
 * restriction.py. Both halves matter: the separators are why the size check is against the
 * non-whitespace quota without having to strip anything, and the sort is why two processes
 * composing the same decisions produce the same digest.
 */
export function serialise(value) {
  if (Array.isArray(value)) return `[${value.map(serialise).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort()
      .map((k) => `${JSON.stringify(k)}:${serialise(value[k])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

/**
 * The pattern naming everything UNDER an ARN. Mirrors restriction.sub_resource.
 *
 * An index holds containers - Resource Explorer reports a bucket and never an object - so the ARN
 * picked for s3:GetObject is the bucket, and arn:aws:s3:::b does not match arn:aws:s3:::b/key.
 *
 * The separator is whichever of ':' or '/' comes FIRST in the resource section, because that is the
 * one following the resource TYPE and a later one belongs to the name. Taking the last separator is
 * the version that looks right and gets arn:aws:logs:…:log-group:/aws/lambda/x wrong.
 */
export function subResource(arn) {
  const head = String(arn).split(':');
  const tail = head.length > 5 ? head.slice(5).join(':') : '';
  const slash = tail.indexOf('/');
  const colon = tail.indexOf(':');
  return (colon >= 0 && (slash < 0 || colon < slash)) ? `${arn}:*` : `${arn}/*`;
}

/**
 * The ARNs one action's statement lists. Mirrors restriction._resources.
 *
 * `nested` answers what generator/actions.Table.under_another_type answers on the writing side:
 * does this action operate BELOW the resource an index can hold. Impact.tsx builds it from the
 * assessment's action_reference, which carries nested_types for exactly this.
 *
 * Only when it does. ssm has no child type, and appending /* to a parameter ARN would put every
 * parameter below it in the same list - under allow_only, a permission nobody granted.
 */
function resourcesFor(restriction, action, nested) {
  const picked = [...(restriction.resources ?? [])].sort();
  if (picked.length === 0 || !nested(action)) return picked;
  return [...new Set([...picked, ...picked.map(subResource)])].sort();
}

/** One action, one statement - before the fold. Mirrors restriction._statement. */
function statement(sid, restriction, action, nested) {
  const base = { Sid: sid, Effect: 'Deny', Action: action };
  if (restriction.intent === 'deny_action') {
    // No resource clause to compose. Byte-identical to the flat Deny an unscopable action gets
    // under deny_only with no resources, so the two fold into one statement.
    return { ...base, Resource: '*' };
  }
  if (restriction.intent === 'tag_condition') {
    return {
      ...base,
      Resource: '*',
      Condition: {
        StringEquals: {
          [`aws:ResourceTag/${restriction.tag_key ?? ''}`]: [...(restriction.tag_values ?? [])].sort(),
        },
      },
    };
  }
  const resources = resourcesFor(restriction, action, nested);
  if (restriction.intent === 'allow_only') {
    // The complement: what is KEPT is listed, so anything not listed - including whatever is
    // created after this is written - is denied.
    return { ...base, NotResource: resources };
  }
  // No resources means the flat deny the container permits for account-level actions only.
  return { ...base, Resource: resources.length ? resources : '*' };
}

/** Everything about a statement except which action it is about. The fold's grouping key. */
function clause(built) {
  const rest = { ...built };
  delete rest.Sid;
  delete rest.Action;
  return serialise(rest);
}

/**
 * Actions whose statement is otherwise byte-identical, collected into one Action list.
 *
 * Mirrors restriction._fold, including the two details that are easy to drop and would show up as
 * different bytes: groups come out sorted by clause, and a lone action stays a string rather than
 * becoming a one-element array.
 */
function fold(built) {
  const groups = new Map();
  for (const one of built) {
    const key = clause(one);
    const names = Array.isArray(one.Action) ? one.Action : [one.Action];
    const set = groups.get(key) ?? new Set();
    for (const name of names) set.add(name);
    groups.set(key, set);
  }
  return [...groups.keys()].sort().map((key, index) => {
    const names = [...groups.get(key)].sort();
    return {
      Sid: `${ADMIN_DENY_SID}${index + 1}`,
      Action: names.length === 1 ? names[0] : names,
      ...JSON.parse(key),
    };
  });
}

/**
 * The PassRole fence, as the writer will compose it.
 *
 * Shown because it is in the same document and spends the same quota, and because an approver
 * reading the policy should not find a statement in the deployed version that the preview did not
 * have. The exemption list here is the placeholder alone - approved mirror ARNs are added by the
 * grant flow and widen it, which is one reason the size is an estimate and the writer measures.
 */
export function fenceStatements(services, accountId) {
  const named = [...new Set(services ?? [])].filter(Boolean).sort();
  return named.map((service, index) => ({
    Sid: `${PASSROLE_FENCE_SID}${index + 1}`,
    Effect: 'Deny',
    Action: 'iam:PassRole',
    NotResource: [`arn:aws:iam::${accountId}:role/mirror-denyrole`],
    Condition: { StringEquals: { 'iam:PassedToService': service } },
  }));
}

/**
 * The whole document, across every policy the administrator touched.
 *
 * Across every policy deliberately. The editor is per policy, but the permission set has ONE inline
 * document and a Deny in it applies whatever policy prompted it - so a per-policy preview would
 * show four documents that do not exist and hide the one that does, including how the four together
 * spend a single 10,240 character quota.
 */
export function composeInline(restrictions,
                              { accountId, fenceServices = [], nested = () => false } = {}) {
  const built = [];
  for (const restriction of restrictions ?? []) {
    for (const action of restriction.actions ?? []) {
      built.push(statement(`${ADMIN_DENY_SID}${built.length + 1}`, restriction, action, nested));
    }
  }
  return {
    Version: '2012-10-17',
    Statement: [...fold(built), ...fenceStatements(fenceServices, accountId)],
  };
}

/** What the document will cost against the quota. */
export function inlineBytes(document) {
  return new TextEncoder().encode(serialise(document)).length;
}

const READ_ORDER = ['Sid', 'Effect', 'Action', 'NotAction', 'Resource', 'NotResource', 'Condition'];

const ordered = (one) => Object.fromEntries(
  Object.keys(one)
    .sort((a, b) => (READ_ORDER.indexOf(a) + 1 || 99) - (READ_ORDER.indexOf(b) + 1 || 99))
    .map((k) => [k, one[k]]),
);

/** The document as a person reads it - indented, keys in the order IAM documents are written. */
export function readable(document) {
  return JSON.stringify({
    Version: document.Version,
    Statement: document.Statement.map(ordered),
  }, null, 2);
}

/**
 * An EXCERPT of a document - statements alone, no Version.
 *
 * Deliberately not document-shaped. A per-policy view rendered with readable() would be a complete,
 * valid, well-formed IAM policy that does not exist anywhere, and an approver who screenshots it has
 * a wrong answer with a screenshot. A bare array cannot be mistaken for the thing that gets written.
 */
export function readableStatements(statements) {
  return JSON.stringify((statements ?? []).map(ordered), null, 2);
}

/**
 * What ONE attached policy puts into the shared document.
 *
 * The permission set has one inline document and every Deny in it applies whatever policy prompted
 * it - which is why composeInline runs across every policy and why a per-policy DOCUMENT would be a
 * lie. This is not that. It composes the whole document once and then reads this policy's
 * contribution back out of it, so every Sid shown is the Sid that will be written.
 *
 * Attribution is by CLAUSE, not by action name, and the difference is not academic. Two policies
 * can restrict the SAME action on different resources - AmazonS3FullAccess on one bucket and a
 * customer managed policy on another - and that is two statements, both carrying s3:GetObject.
 * Matching on the name put both of them in both excerpts, so each policy's view showed a Deny on a
 * bucket it had nothing to do with. So this rebuilds the clause each of this policy's decisions
 * folds into, using the same statement() and clause() the fold itself uses, and matches on that.
 *
 * Three more things that only fall out of doing it this way round:
 *
 *   the Sids have GAPS          AdminDeny1 and AdminDeny4 with nothing between them, because 2 and
 *                               3 came from another policy. The gaps are the proof that this is a
 *                               view of something bigger. Renumbering would produce a document that
 *                               does not exist.
 *   statements are SHARED       the fold groups by resource clause, not by policy, so one statement
 *                               can carry actions from two policies. Both excerpts show it, whole,
 *                               with `others` naming what came from elsewhere. Showing a trimmed
 *                               copy would be showing a statement nobody will write.
 *   the cost is MARGINAL        `share` is what the document grows by BECAUSE of this policy, not
 *                               the sum of the bytes of the statements above. A policy whose actions
 *                               all fold into a statement another policy already pays for costs
 *                               only its action names, and the sum would double-count every byte
 *                               of the resource clause they share.
 *
 * The PassRole fence is in neither figure: it is composed from the assessment's grants and is the
 * same with or without this policy's restrictions, so it cancels out of the subtraction. It is
 * returned separately, filtered to the services THIS policy's grant names.
 */
export function policyContribution(restrictions, policy, options = {}) {
  const all = (restrictions ?? []).filter((r) => (r.actions ?? []).length > 0);
  const document = composeInline(all, options);
  const without = composeInline(all.filter((r) => r.policy !== policy), options);

  // Which actions this policy puts into which clause. The same two functions the fold uses, so the
  // key is the fold's own key and a decision lands where its statement lands.
  const nested = options.nested ?? (() => false);
  const mine = new Map();
  for (const restriction of all) {
    if (restriction.policy !== policy) continue;
    for (const action of restriction.actions ?? []) {
      const key = clause(statement('', restriction, action, nested));
      const held = mine.get(key) ?? new Set();
      held.add(action);
      mine.set(key, held);
    }
  }

  const statements = [];
  for (const one of document.Statement) {
    const held = mine.get(clause(one));
    if (!held) continue;
    const names = Array.isArray(one.Action) ? one.Action : [one.Action];
    const ours = names.filter((n) => held.has(n));
    if (ours.length === 0) continue;
    statements.push({ statement: one, ours, others: names.filter((n) => !held.has(n)) });
  }

  const fenced = new Set(options.policyFenceServices ?? []);
  const fence = document.Statement.filter(
    (one) => fenced.has(one.Condition?.StringEquals?.['iam:PassedToService']),
  );

  const total = inlineBytes(document);
  return {
    statements,
    fence,
    total,
    without: inlineBytes(without),
    share: total - inlineBytes(without),
  };
}
