#!/usr/bin/env python3
"""Generate server/serviceIcons.generated.js - IAM service prefix -> AWS icon file.

    python3 tools/build-service-icons.py

Why this is generated rather than written
-----------------------------------------
The hand table in serviceIcons.js mapped 70 prefixes. The icon deck ships 291 files and AWS has
455 IAM service prefixes, so 232 icons (80%) reached nothing and every service outside the 70 got
no icon at all - silently, because an unmapped prefix renders nothing by design.

Nothing derivable connects an IAM prefix to a brand: s3 is Simple Storage Service, ecr is Elastic
Container Registry, events is EventBridge. That was the reason for a hand table, and it was wrong -
botocore carries the bridge. Every service model has a serviceFullName, which is the brand, and an
endpointPrefix and signingName, which are what IAM keys on:

    ecr    -> "Amazon Elastic Container Registry"  -> Amazon-Elastic-Container-Registry.svg
    s3     -> "Amazon Simple Storage Service"      -> Amazon-Simple-Storage-Service.svg
    events -> "Amazon EventBridge"                 -> Amazon-EventBridge.svg

That is the same source the action table's projection 6 already joins against, so it is a
dependency this repository's sibling already carries rather than a new one.

What this does NOT do
---------------------
It never guesses. A prefix whose brand does not match an icon FILE NAME produces no entry, and the
hand table in serviceIcons.js stays as the override layer for exactly those - kafka is branded
"Managed Streaming for Kafka" by botocore and "Amazon Managed Streaming for Apache Kafka" by the
icon deck, and no normalisation should be asked to bridge a missing word. Decisions the generator
cannot make also live there: logs and cloudwatch are one brand, and only a person knows that.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / 'public' / 'aws-icons'
OUT = ROOT / 'server' / 'serviceIcons.generated.js'

VENDOR = re.compile(r'^(amazon|aws)')


def norm(text: str) -> str:
    return re.sub(r'[^a-z0-9]', '', (text or '').lower())


def main() -> int:
    try:
        from botocore.session import get_session
    except ImportError:
        print('botocore is required: pip install botocore', file=sys.stderr)
        return 2

    files = sorted(p.stem for p in ICON_DIR.glob('*.svg'))
    if not files:
        print(f'no icons in {ICON_DIR} - run tools/extract-aws-icons.mjs first', file=sys.stderr)
        return 2

    # Both spellings of every file, so "AWS Lambda" and "Lambda" both find AWS-Lambda.svg. First
    # writer wins, and the list is sorted, so the mapping is deterministic across runs.
    by_name: dict[str, str] = {}
    for stem in files:
        key = norm(stem)
        by_name.setdefault(key, stem)
        by_name.setdefault(VENDOR.sub('', key), stem)

    session = get_session()
    # prefix -> brand. A service answers to its endpoint prefix, its signing name and its botocore
    # name, and IAM uses whichever AWS chose; all three are recorded.
    brand: dict[str, str] = {}
    for service in session.get_available_services():
        try:
            meta = session.get_service_model(service).metadata
        except Exception:  # noqa: BLE001 - a model that will not load is one service, not a failure
            continue
        full = meta.get('serviceFullName')
        if not full:
            continue
        for key in {meta.get('endpointPrefix'), meta.get('signingName'), service}:
            if key:
                brand.setdefault(key, full)

    found: dict[str, str] = {}
    for prefix, full in sorted(brand.items()):
        # The brand, then the brand without its vendor word, then the prefix spelled as a brand.
        # Never a prefix match or a containment: "es" would find Elastic Beanstalk.
        for candidate in (norm(full), VENDOR.sub('', norm(full)), norm(prefix)):
            if candidate in by_name:
                found[prefix] = by_name[candidate]
                break

    body = '\n'.join(f'  {json.dumps(k)}: {json.dumps(v)},' for k, v in sorted(found.items()))
    OUT.write_text(
        '// GENERATED by tools/build-service-icons.py - do not edit.\n'
        '//\n'
        '// IAM service prefix -> AWS Architecture Icons file, joined through botocore\'s\n'
        "// serviceFullName. Every entry's file is checked to exist by serviceIcons.test.js.\n"
        '//\n'
        '// A prefix missing here is one whose brand does not match any icon file name. That is not\n'
        '// a gap to paper over with a looser match - it is what the hand table in serviceIcons.js\n'
        '// is for, and the hand table overrides this one wherever both have an answer.\n'
        f'\nexport const GENERATED_SERVICE_ICONS = {{\n{body}\n}};\n',
        encoding='utf-8',
    )
    print(f'{len(found)} prefixes -> {OUT.relative_to(ROOT)}')
    print(f'  icon files: {len(files)}   services botocore knows: {len(brand)}')
    unmatched = sorted(set(brand) - set(found))
    print(f'  no icon for {len(unmatched)} prefixes, e.g. {", ".join(unmatched[:8])}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
